services:
  gminer:
    build:
      context: .
      dockerfile: Dockerfile
    runtime: nvidia
    command: --algo 144_5 -s stratum+ssl://zhash.auto.nicehash.com:443 -u 34qDhCVPG7wHXNi9MrYAEKcwg7SGvngdRy.ryou --pass x --pers nicehash



    
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]