services:
  gminer:
    image: ghcr.io/korewachino/gminer:latest
    build:
      context: .
      dockerfile: Dockerfile
    runtime: nvidia
    env_file:
      - .env
    command: $ARGS



    
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]